### ISSUE TITLE
covid_19_india.csv is unavailable now

### ISSUE THREAD

**Issue by kksargar** [rahulnyk/COVID19_IndiaData#3]
Kindly check. Data is unavailable.

**Comment by rahulnyk** [comment]
Hi, 
Since I am using this repo to maintain R code, I have moved the data to the following dedicated repo.

https://github.com/rahulnyk/covid19_india_data

The data is being updated twice a day. 
Thanks for using it. 

Rahul

**Comment by kksargar** [comment]
Thank you
